### ISSUE TITLE
Question: Missing login?

### ISSUE THREAD

**Issue by ymhmd** [cliccato/IvaAE#1]
Hi,

Thanks for sharing this python API. 

As per my understanding, this API to get some data from `ivaservizi.agenziaentrate.gov.it`, to use this endpoint do we need any kind of login?

Thanks!

**Comment by cliccato** [comment]
Hello!

Yes, to use the ivaservizi.agenziaentrate.gov.it API endpoint, you need to provide the company's registration number and the cash register number. There is no traditional login with a username and password required, but you will need to include this information as parameters in your API request.

Make sure you have the correct company's registration number and cash register number to successfully access the desired data from the API.

I hope this information is helpful! Let me know if you have any other questions.

**Comment by ymhmd** [comment]
@cliccato, thanks a lot for clarification. 

I asked this question to understand how I can do the login to access Agenzia delle Entrate portal to get users' data. I've figured out this login part and developed some REST APIs to do SPID login then get the requested users' data (i.e. Precompilata, Certificazione Unica, Spese Sanitaria ...etc). I hope sharing this REST API can help anyone who want to integrate with Agenzia delle Entrate.
Here is the REST APIs swagger - https://www.api.domaniservice.com/v1/static/index.html
